-- 코드를 입력하세요
SELECT
    DATE_FORMAT(A.SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
    A.PRODUCT_ID,
    A.USER_ID,
    A.SALES_AMOUNT
FROM ONLINE_SALE A
WHERE A.SALES_DATE >= '2022-03-01' AND A.SALES_DATE < '2022-04-01'

-- MYSQL은 FULL JOIN이 없으므로 UNION 활용
UNION ALL

-- 중복 제거를 위해 왼쪽에 없는 것만 추가
-- NULL AS 뒤에는 테이블 접두어가 올 수 없음
SELECT
    DATE_FORMAT(B.SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
    B.PRODUCT_ID,
    NULL AS USER_ID,
    B.SALES_AMOUNT
FROM OFFLINE_SALE B
WHERE B.SALES_DATE >= '2022-03-01' AND B.SALES_DATE < '2022-04-01'

ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;
 