-- 코드를 입력하세요
SELECT A.NAME, A.DATETIME       # 각각 AS 활용해서 별칭을 지어줬으므로, 별칭으로 불러온다.
FROM ANIMAL_INS AS A
LEFT JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY A.DATETIME ASC
LIMIT 3;