-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER U
JOIN USED_GOODS_BOARD B ON U.USER_ID = B.WRITER_ID
WHERE B.STATUS = 'DONE'
GROUP BY U.USER_ID, U.NICKNAME
-- 집계함수(SUM, COUNT, AVG 등)의 결과를 필터링할 때는 HAVING 을 사용
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC;